---
# tasks file for ansible-role-devtools

- name: Install Development Tools
  apt: 
    name: build-essential
    state: present
  become: true
  become_user: root


- name: Ensure that the required packages are present
  apt: name={{ item }} state=present
  become: true
  become_user: root
  with_items:
      - zlib1g-dev  
      - wget
      - sed

- name: Install Python pip
  apt:
    name: python-pip
  become: true
  become_user: root

- name: Install ftp and python-devel
  apt: name={{ item }} state=present
  with_items:
      - python-dev
      - ftp

- name: Install java
  apt:
    name: default-jre
    state: present
  become: true
  become_user: root
  
