---
# tasks file for ansible-role-devtools

- name: Install Development Tools
  apt: 
    name: build-essential
    state: present
  become: true
  become_user: root


- name: Ensure that the required packages are present including Python PIP
  apt: name={{ item }} state=present
  become: true
  become_user: root
  with_items:
      - zlib1g-dev  
      - wget
      - sed
      - python-dev
      - ftp
      - default-jre
      - python-pip
      - mercurial
